### ISSUE TITLE
Two sensors ?

### ISSUE THREAD

**Issue by mycanaletto** [mkotler/ad-automoli#14]
Hello,
Great idea to take over this project and bring it back to life!

I've seen that you've dealt with quite a few conditions for switching off. But not for switching on.

What I'd like is the possibility of switching on if a lamp is already on. In fact, change its color.

Let me explain what I tried with two automoli inputs:

```
auto_sdb_strip_global:
  module: automoli
  class: AutoMoLi
  room: aa
  motion_state_on: "on"
  motion_state_off: "off"
  delay: 300
  daytimes:
    - { starttime: "00:01", name: day, light: "scene.led_strip_sdb_blue" }
  lights: light.led_strip_sdb
  motion: binary_sensor.global_motion

auto_sdb_strip:
  module: automoli
  class: AutoMoLi
  room: aa
  motion_state_on: "on"
  motion_state_off: "off"
  delay: 100
  daytimes:
    - { starttime: "07:30", name: day, light: "scene.led_strip_sdb_day" }
    - { starttime: "00:10", name: night, light: "scene.led_strip_sdb_night" }
  lights: light.led_strip_sdb
  motion: binary_sensor.ec4d3ec370f4_motion
```

I have a first sensor that lights a global zone in blue via a scene.

I'd like a second sensor in a more precise zone that switches the blue scene to white.

The problem is that if the lamp is already lit in blue, atomoli considers that it's already lit and does nothing.

Ideally, of course, automoli should manage both sensors in a single automoli.... input.

Or maybe remove the check if the lamp is already on from the `automoli.py` code?

Merci ;-)

lionel

**Comment by TonnyMunkNielsen** [comment]
From the get_state it would be possible to fetch the color/scene and see if it matches the one set in that given automation.

I'm scared of how this will affect the manual controls. If I happen to change color manually, we do not want this to be overridden by an automation... So somehow the global automation would have to be tagged as "overridable", but I'm not sure it's a good idea or how difficult it would be.

I think we would need Mr. @mkotler's input on the technical feasibility.

**Comment by mkotler** [comment]
Thanks @mycanaletto for giving this version a try and for the feedback.  You are right that I had not considered color or scene changes. 

I think the simplest solution is to just honor "on" changes even when the light is already on.  As @TonnyMunkNielsen mentions this would cause manual color changes to be overridden by one of the motion sensors (but I think that might be an acceptable limitation for at least some scenarios).  

The challenge with trying to be smart here with "overridable" is there are likely times when you want the motion to override and cases when you don't.  And how long should the change be sticky? For example, if you change the color manually do you want it to stay that way until another color change, until the light turns off, or just until the next motion.  

I'll continue to think about this (and welcome any other ideas!) and will take a look at a code change this weekend.

**Comment by mycanaletto** [comment]
Thanks for the reply!

For the record, I tried to do this with automation. But I'd rather do it with Automoli because it's easier to deploy. Automoli will also take humidity into account.

Thanks for your help!

```
alias: GUI - Led Strip SdB
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.motion_bureau
    to: "on"
    id: sdb_to_on
  - platform: state
    entity_id:
      - binary_sensor.motion_bureau
    to: "off"
    id: sdb_to_off
    for:
      hours: 0
      minutes: 3
      seconds: 0
  - platform: state
    entity_id:
      - binary_sensor.mi_motion_garage
    to: "on"
    id: hall_to_on
  - platform: state
    entity_id:
      - binary_sensor.mi_motion_garage
    to: "off"
    id: hall_to_off
    for:
      hours: 1
      minutes: 0
      seconds: 0
  - platform: template
    value_template: |
      {{ is_state('binary_sensor.motion_bureau', 'off') and is_state('binary_sensor.mi_motion_garage', 'off') }}
    id: all_to_off
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.disable_automoli_sdb_strip
    state: "on"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id in ['sdb_to_on'] and is_state('binary_sensor.night_reworked', ['on'] )}}
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_day
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id in ['sdb_to_on'] and is_state('binary_sensor.night_reworked', ['off'] )}}      
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_night
      - conditions:
          - condition: trigger
            id:
              - sdb_to_off
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_blue
      - conditions:
          - condition: trigger
            id:
              - hall_to_on
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_blue
      - conditions:
          - condition: trigger
            id:
              - all_to_off
        sequence:
          - service: light.turn_off
            entity_id: light.led_strip_sdb
mode: restart
```
