### ISSUE TITLE
Support different actions after the delay besides turning off the lights that were turned on

### ISSUE THREAD

**Issue by mkotler** [mkotler/ad-automoli#15]
🙄 **Is your feature request related to a problem? Please describe.**
This feature request was spurred by @mycanaletto in issue14.  The fix for the original issue enabled running scenes instead of just turning lights on. But then there was a need to be able to return to the original scene after the delay.  

😍 **Describe the solution you'd like**
To address this request, I'm going to add a lights_off parameter.  lights_off can include switches and lights (just like the lights parameter) and also scenes.  

This is **big**!  To make things even more powerful, lights and lights_off (and even daytimes) should even support running scripts.

**Comment by mycanaletto** [comment]
At a time when the core tends to be more and more GUI-based, it's great that Automoli is evolving. At first, I wasn't too keen on yaml, but now I find it much more practical!

If you can execute an output action, it opens the door to a lot of possibilities.

In fact, I'm going to write an article on my [blog](https://www.canaletto.fr/) about these possibilities and, above all, about getting to grips with Automoli again.

I ended up abandoning [Schedy](https://hass-apps.readthedocs.io/en/stable/apps/schedy/) for direct yaml, but I'm still a fan of [ControllerX](https://xaviml.github.io/controllerx/) !

**Comment by mkotler** [comment]
@mycanaletto, please try out automoli.py in the [issue15 branch](https://github.com/mkotler/ad-automoli/tree/issue15).  This is a pretty major re-rewrite both to add the lights_off argument and also to properly handle scenes and scripts across lights, lights_off, and daytime arguments.  Note that scripts/scenes will only run once - if they are in lights or daytimes then when the lights are turned on or the daytime is switched or if they are in lights_off then when the lights are turned off.  

I have gone a number of test cases but I expect there may still be bugs so will be running it for a while to see if there is any strange behavior and I would appreciate any feedback you have as well.  

I've spent most of my career working on GUI experiences, so it is quite ironic that I also fell back to yaml for configuring home assistant! :)

**Comment by mycanaletto** [comment]
It seems to work, but I wonder what the output time is.

In my configuration, the first global input lights up blue.

The second will light up white when you enter.

And it's the first input that will eventually turn off...

In this mode of operation, I think there should be a `delay_light_off:` parameter?

Or is there something I haven't understood?

```
auto_sdb_strip_global:
  module: automoli
  class: AutoMoLi
  room: a_sdb_global
  motion_state_on: "on"
  motion_state_off: "off"
  delay: 3000                         # long time ...
  daytimes:
    - { starttime: "06:29", name: more_night, light: 0 }
    - { starttime: "06:30", name: day, light: "scene.led_strip_sdb_blue" } # Global zone : blue
  lights: light.led_strip_sdb
  motion: binary_sensor.motion_global

auto_sdb_strip:
  module: automoli
  class: AutoMoLi
  room: a_sdb
  motion_state_on: "on"
  motion_state_off: "off"
  delay: 100
  daytimes:
    - { starttime: "06:30", name: more_night, light: 0 }
    - { starttime: "07:30", name: day, light: "scene.led_strip_sdb_day" }     # Private zone : white
    - { starttime: "00:10", name: night, light: "scene.led_strip_sdb_night" }
  lights: scene.led_strip_sdb_blue
  lights_off: scene.led_strip_sdb_blue
  motion: binary_sensor.motion_private
```

Or manage everything (global sensor and its action) in the same input?

```
  lights_pre_load: scene.led_strip_sdb_blue
  motion_pre_load: binary_sensor.motion_global

  lights_off: scene.led_strip_sdb_blue
  delay_off: 3000
```
In practice, the aim is that if someone crosses the corridor, the bathroom is lit in blue (it's visible) and if someone enters the bathroom, it's lit in white for as long as that person is in the bathroom. So you don't want the external sensor to end up switching off the bathroom while someone's inside...

I think this case can be transposed to other uses.

**Comment by mkotler** [comment]
If I am understanding the scenario and how your setup works, I don't think you need lights_off configured at all.  Instead in auto_sdp_strip_global, add block_off_switch_entities with the motion sensor for the bathroom (binary_sensor.motion_private). That will prevent the corridor from turning off until after there is no motion in the bathroom.

lights_off works well for a few scenarios. For example, if you wanted to return to the blue RGB after leaving the bathroom instead of turning the lights off. Or, if you want to execute a script in addition to (or less likely instead of) turning off the lights, like notifying your phone that the lights went off.

**Comment by mycanaletto** [comment]
I tried block_off_switch_entities: without success, but block_on_switch_states: seems to work.

`auto_sdb_strip_global:` switches to blue

`auto_sdb_strip: `switches from white to blue on output

`auto_sdb_strip_global:` switches to off, but too fast or too long if you increase the delay.

In fact, `lights_off:` is missing a delay to really switch to off, so that you don't have to wait for `auto_sdb_strip_global:`

**Comment by mkotler** [comment]
Hmm, I am confused by a few things with your reply. Apologies for my long reply but let me try to explain a few things in detail to make sure they are clear. 

First, let me explain block_off and block_on. In both cases you need both entities and states. block_on says before turning on the lights check if any of the block_on_switch_entities have block_on_switch_states. If they do then do not turn the lights on.  block_off does the same thing but blocks turning the lights off if any block_off_switch_entities have block_off_switch_states.  For example, I have a binary_sensor that looks at the weather and sun position and if it is really sunny it has the state "on" and will block turning on certain lights.  For block_off, my bathroom has a different light in the shower and lights outside the shower.  I use humidity and temperature to not turn off the shower light but I prevent turning off the lights outside the shower if the shower light itself is on using block_off (so I don't step out of the shower in the dark).  

As I said, I don't think you need lights_off here at all.  Here's what I expected was the solution.  I would think that motion sensor 1 turns the bathroom light to blue and if you don't go into the bathroom and trip motion sensor 2 the blue light will go off after a certain delay. But if you go into the bathroom, it changes to white and it stays on for the delay there or as long as there is motion with motion sensor 2 (see note 1 below).  Then once the delay passes after no motion has been detected it will turn off.  The problem I thought you had is that the delay for turning the light blue ends up turning the light off even after you change it to white.  But if you use block_off alongside the blue/motion sensor 1 you can prevent it from turning off.  I suggested above using block_off with motion sensor 2 but that may not have been the right solution (see note 2 below).  

Note 1: The motion for a certain room doesn't just cause the lights to turn on but it resets the delay whenever motion triggers. Motion sensors have a detected (on) and cleared state (off). Lights go on as soon as motion is detected and the delay timer starts when motion clears.  But if motion is detected a second time the timer is reset.  So lights will go off in a room the delay number of seconds after the last motion is cleared.  

block_off actually also just resets the timer. Let's say a room has a 60 second delay but a block_off if the day is Monday (just for a silly example).  Monday night you trigger the light on, 60 seconds later it goes to turn off but it's Monday so it waits another 60 seconds and checks again. It will keep checking every minute and finally just after midnight another 60 seconds will have passed and it will be Tuesday and the lights will finally go off.  

Note 2: I said to block_off using a motion sensor but that was probably the wrong thing depending on the type of motion sensor (see note 3) because as soon as the motion sensor switches to off, after the next delay the block_off check will fail and the lights would go off. What you probably want instead is to prevent it from turning off as long as the light is white. A scene will not report as on but if the rgb light itself will report as on you can use that to block_off.  

Note 3:  I mentioned it depends on the motion sensors.  There are generally two that I use.  I have a number of sensors that detect when you cross the sensor, turn on and then almost immediately turn off.  PIR (passive infrared) sensors behave this way. Then there are motion sensors that detect presence and will stay on as long as they detect presence (like aqara sensors). I was thinking of the second type in my original solution - if your bathroom motion sensor stayed on for a while then it might work to block turning the lights off.  But if the motion sensor turns on and then immediately off it won't work. 

I hope all of this makes sense.  If it doesn't, if you can tell me the type of RGB light you have and the type of motion sensor, I can try to construct a yaml that will work (hopefully).

**Comment by mycanaletto** [comment]
Thank you for all these explanations and your passion for this kind of implementation.

My first sensor is an Aqara basic which stays on for the time of the passage (1 minute), while the second is an Aqara P1 which has the notion of occupancy (10 minutes). The led band is RGBCCT. I know there are more advanced sensors, but they need to be powered, which won't be possible.

Once again, my goal (non-existential... fun) is to go back to blue if there's no more activity in the bathroom, and to switch off after a longer delay if there's no activity on the two sensors.

Perhaps Automoli isn't the right approach for what I want to do, as I think it would have to be managed in a single input capable of handling both sensors, which would require major modifications.

I had started an automation in yaml ([in the other post](https://github.com/mkotler/ad-automoli/issues/14#issuecomment-1969083665)) that I could complete with the humidity constraint so as not to switch off if someone takes a shower and also place a door contact.

**Comment by mkotler** [comment]
Separate update on this feature request:  As I continue to think about this update, I am uncomfortable with the current implementation making the core automoli functionality more complex (and buggy both because of code errors and potential for user confusion).  

Rather than supporting scripts and scenes in lights and lights_off, I want to keep lights pure.  Anything in lights will be turned on and turned off.  Instead, I am considering adding "after_on" and "after_off".  after_on would execute separately after the lights are turned on and after_off after the lights are turned off.  It would still support all the same scenarios but keep the logic of when lights go on/off simpler.  Feedback welcome but this will be my next change when I have time.

**Comment by mycanaletto** [comment]
I haven't had time to work on it again.

That said, I understand your logic and `after_on / after_off` seems like a good idea to maintain a certain consistency.

**Comment by mkotler** [comment]
I pushed a new version to the issue15 branch. Scripts and scenes are now blocked in the lights entities but allowed in after_on, after_off, and daytimes. 

When you have a chance, try it out and let me know if you have any feedback.  I am going to run with it this week and if all looks good plan to merge it back to main next weekend.

**Comment by mycanaletto** [comment]
I tested, the scenes are ok in after_off, but not the scripts...

**Comment by mkotler** [comment]
Hmmm, can you share your config? And if possible what your script does?  I have a simple script that just calls the notify service on my phone and it launches fine in after_off.

**Comment by mycanaletto** [comment]
Really not much. And if I launch it manually, it works.

```
auto_sdb_strip:
  module: automoli
  class: AutoMoLi
  room: a_sdb
  motion_state_on: "on"
  motion_state_off: "off"
  delay: 15
  daytimes:
    - { starttime: "06:30", name: more_night, light: 0 }
    - { starttime: "07:30", name: day, light: "scene.led_strip_sdb_day" }
    - { starttime: "00:10", name: night, light: "scene.led_strip_sdb_night" }
  lights: 
    - light.led_strip_sdb
  # after_on: 
  after_off: script.1710171206878
  motion:
    - binary_sensor.test_sdb
  disable_switch_entities:
    - input_boolean.disable_automoli_sdb_strip
```

```
alias: GUI - Exit Strip SdB
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.groupe_d_ampoules_led
            state: "on"
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_blue
  - choose:
      - conditions:
          - condition: state
            entity_id: light.groupe_d_ampoules_led
            state: "off"
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_blue
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          - service: light.turn_off
            metadata: {}
            data:
              transition: 60
            target:
              entity_id: light.led_strip_sdb
mode: single
```

**Comment by mkotler** [comment]
I don't have time to test your exact script right now but just in case it's the script, could you see if my script works (obviously replacing notify.mobile_app_your_phone with the right service call for you)?

```
send_phone_notification:
  alias: Send phone notification
  sequence:
  - service: notify.mobile_app_your_phone
    metadata: {}
    data:
      message: Hello world!
  mode: single
```

**Comment by mycanaletto** [comment]
I understand what happened.

I created this script quickly in GUI and AddDaemon doesn't know it. Relaunching AppDaemon works fine, the script launches with after_off!

I'll be able to see what avenue I'm exploring!

**Comment by mkotler** [comment]
Glad to hear it works!  I am a little surprised that the new script required restarting AppDaemon though. I doubt this is the case but, by any chance, do you use the production_mode setting in your AppDaemon configuration file?  If you are (and it is set to true) automoli won't reload when you updated the app config. Otherwise, it is a mystery to me - but glad that the code works at least.

**Comment by mycanaletto** [comment]
For my scenario, I've done things a bit differently: I consider that the state of the bathroom lighting before automoli goes into action is managed by other scripts/automations.

So I'm only concerned with the output conditions, and the script launched with after_off is perfect.

However, calling an external script is contrary to Automoli's philosophy, where the idea is that everything should be included...

So I was thinking it might be possible to consider scripting this directly in Automoli?

I made this script as an output :

```
script:
  light_exit_strip_sdb:
    alias: "Light Exit Strip SdB"
    mode: single
    icon: mdi:led-strip-variant-off
    sequence:
      - choose:
          - conditions: "{{ is_state('light.groupe_d_ampoules_led', 'on') and is_state('switch.lidl_multiprise_l3', 'off') }}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.led_strip_sdb_blue
          - conditions: "{{ is_state('light.groupe_d_ampoules_led', 'on') and is_state('switch.lidl_multiprise_l3', 'on') }}"
            sequence:
              - service: light.turn_on
                data:
                  color_name: blue
                  brightness_pct: 5
                target:
                  entity_id: light.led_strip_sdb
          - conditions: "{{ is_state('light.groupe_d_ampoules_led', 'off') }}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.led_strip_sdb_blue
              - delay:
                  hours: 0
                  minutes: 1
                  seconds: 0
                  milliseconds: 0
              - service: light.turn_off
                data:
                  transition: 60
                target:
                  entity_id: light.led_strip_sdb
```
But we could imagine:

```
  after_off: 
    - if light.one,on and switch.one,off do scene.led_strip_sdb_blue
    - if light.one,on and switch.one,on do scene.led_strip_sdb_white
```
Or directly in script language :
```
  after_off: 
    - script:
      - conditions:
          - condition: state
            entity_id: light.groupe_d_ampoules_led
            state: "off"
        sequence:
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.led_strip_sdb_blue
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          - service: light.turn_off
            metadata: {}
            data:
              transition: 60
            target:
              entity_id: light.led_strip_sdb
```
This is just my imagination and I guess it would really complicate development....
